### ISSUE TITLE
Downgrade to 1.21?

### ISSUE THREAD

**Issue by SnabbSpelare** [Command17/Hammering#4]
**Describe the feature**
I am requesting a version of the Hammering mod compatible with Minecraft 1.21. Many mods in my modpack are specifically for 1.21, so this downgrade would make your mod usable in my setup.

**Additional context**
Your mod looks fantastic, and I’d love to include it. Hammering down this problem would help a lot—thank you!

**Comment by uuComma** [comment]
Should work, but I'll leave this open for now

**Comment by SnabbSpelare** [comment]
> Should work, but I'll leave this open for now

Thank you I should've tried it before making this. Just by default if it isn't 1.21.x i think it is outdated. By the way, I am no longer in need of that version as I've moved to 1.21.4 the latest version to wait for all mods to be updated instead of waiting for a fork/port. Thank you very much for paying attention and replying! I can't wait to try this. Anyway please make sure your mod says it is 1.21.x which means all versions in that release. Additionally i would suggest adding links to where to find your mod.

Edit: Just a heads up I think that disabling the enhancement when sneaking is smart but if this mod was used on a PvP server or setting that means it's basically a useless enchantment. This is a super minor thing so I don't expect anything to be done about it. Just a food for thought.

Also why is there no information about what Minecraft versions it supports on GitHub? Or is it just in "Releases"?

**Comment by uuComma** [comment]
First of all, thank you for your kind words!

1.21.4 will come but I don't want to make many changes currently because I'm working on a library (which is almost done) for this mod and my future mods (1.21.4 may come before that but I don't know)

>Also why is there no information about what Minecraft versions it supports on GitHub? Or is it just in "Releases"?

Github is just not where people find my mods so I don't really see the need in saying what version the mod supports

Also, unrelated to the above, but just so you know I read your entire message, I just don't know how to answer it all

**Comment by SnabbSpelare** [comment]
Thank you for your reply and for reading my message—I appreciate it! I’ll keep things shorter in the future.

I understand your approach, but personally, I would add versions and links to the mod site it’s uploaded on to make it easier for users to find the mod. That said, I’m more of a resource pack creator than a modder, so I completely respect your decision.

Thanks again for your hard work!
